### PR TITLE
Bump to 4.9.165

### PR DESCRIPTION
**Pull request by karljohns0n**
The SCL repository is needed to build this release with devtoolset-7:

http://mirror.centos.org/centos/$releasever/sclo/$basearch/rh/

It seems to be here on the cbs:

http://cbs.centos.org/repos/sclo6-devtoolset-7-rh-release/x86_64/os/Packages/
http://cbs.centos.org/repos/sclo7-devtoolset-7-rh-release/x86_64/os/Packages/

### CODE REVIEW

**Comment by sheep** [comment]
Hi Karl, thanks for your PR!

But the package doesn't build like this, CBS doesn't found the devtoolset-*. I think we need to add `centos-release-scl-rh` to the buildrequires.

**Comment by sheep** [comment]
Actually, adding the package `centos-release-...` doesn't work...

**Comment by karljohns0n** [comment]
The SCL repo needs to be enable before building the package (ie: not by adding the repo package in the BuildRequires section). On my mock setup the SCL repo is always enabled but I can't say how to use it on the CBS. Hopefully it's possible..

**Comment by sheep** [comment]
I've created a bug report: https://bugs.centos.org/view.php?id=15462
which I hope just asked to have the scl repo in CBS.

**Comment by pasikarkkainen** [comment]
@karljohns0n thanks a lot!

**Comment by sheep** [comment]
Looks good, thanks!

**Pull request merged**
